apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-model-loader
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: model-loader
        image: ollama/ollama:latest